# Check for admin rights
if (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Output "WinGet needs Administrator rights to run. Restarting in Admin mode..."
    Start-Process -Verb runas -FilePath powershell.exe -ArgumentList "iwr -useb https://raw.githubusercontent.com/robert-cpl/winget-dsc/main/run-configuration.ps1 | iex"
    break
}

Write-Host "See full source code on GitHub @ https://github.com/robert-cpl/winget-dsc" -ForegroundColor Green

# Local development variables
$isLocalDevelopment = $false

# Variables
$defaultDscProfile = "personal"
$dscProfiles = @("personal", "developer")

# User Input
function GetUserInput {
    param(
        [string]$message,
        [string[]]$choices,
        [string]$defaultValue
    )

    while ($true) {
        # User input
        Write-Host "$message Press ENTER for default value ($defaultValue)." -ForegroundColor Green
        $userInput = Read-Host

        # Validation
        $userInput = $userInput.ToLower()
        if ($userInput -eq "") {
            return $defaultValue
        }

        if ($choices -notcontains $userInput) {
            Write-Host "Invalid input, try again." -ForegroundColor Yellow
            continue
        }
        break
    }
    return $userInput
}

$dscProfile = GetUserInput -message "What DSC profile you want to install? ($($dscProfiles -join '/' ))." -choices $dscProfiles -defaultValue $defaultDscProfile

# Configuration file path setup
$configurationFolderPath = "./winget-configuration"
if (!(Test-Path $configurationFolderPath)) {
    Write-Host "Creating configuration folder at '$configurationFolderPath'."
    New-Item -ItemType Directory -Path $configurationFolderPath
}

$configurationFileName = "configuration.dsc.yaml"
$configurationFilePath = "$configurationFolderPath/$configurationFileName"

# Modules
$fileFolderPath = if ($isLocalDevelopment) {"./configurations"} else {"https://raw.githubusercontent.com/robert-cpl/winget-dsc/main/configurations"}
$header = iwr -useb "$fileFolderPath/modules/header.yaml"
$headerContent = $header.Content
$footer = iwr -useb "$fileFolderPath/modules/footer.yaml"
$footerContent = $footer.Content

# DSC's
$sharedConfig = iwr -useb "$fileFolderPath/shared.yaml"
$sharedConfigContent = $sharedConfig.Content
$personalConfig = iwr -useb "$fileFolderPath/personal.yaml"
$personalConfigContent = $personalConfig.Content
$developerConfig = iwr -useb "$fileFolderPath/developer.yaml"
$developerConfigContent = $developerConfig.Content

if ($dscProfile -eq $defaultDscProfile) {
    Write-Host "Using $dscProfile DSC configuration." -BackgroundColor Yellow
    $configType = $personalConfigContent
} else{
    Write-Host "Using $dscProfile DSC configuration." -BackgroundColor Yellow
    $configType = $developerConfigContent
}

# Build the DSC configuration file
$headerContent, $sharedConfigContent, $configTypeCOntent, $footerContent | Set-Content -Path $configurationFilePath

# Run the configuration
winget configuration --file $configurationFilePath 

#Cleanup
Write-Host "Deleting autogenerated configuration file created at '$configurationFolderPath'."
Remove-Item $configurationFolderPath
